### ISSUE TITLE
Is there a reference for translation?

### ISSUE THREAD

**Issue by chlizheng** [revng/revng#10]
HI.
I want to translate ARM assembly code to llvm-ir staticly and use a simple example to try it. But I'm a new hand and did'nt find enough data about it.  Are there good reference data for translation?
best regards.

**Comment by aleclearmind** [comment]
Hi, sorry for the delay. Please take a look at the [getting started](https://rev.ng/getting-started.html) page and to the [docs](https://github.com/revng/revng/tree/develop/docs) directory.
