### ISSUE TITLE
ptc.h: No such file or directory

### ISSUE THREAD

**Issue by sonnylier** [revng/revng#11]
Hi~
When I make revamb project, I get  this error:
```
revamb/ptcinterface.h:14:17: fatal error: ptc.h: No such file or directory
revamb/ptcinterface.h:14:17: fatal error: ptc.h: No such file or directory
```
Can you tell how to solve this  issue?
Best regards!

**Comment by fritzone** [comment]
Same here!

**Comment by aleclearmind** [comment]
Hi, sorry for the delay in answering. We just pushed a new set of changes.

You shouldn't use this repository directly, use [orchestra](https://github.com/revng/orchestra), which will handle all the dependencies for you ([ptc.h](https://github.com/revng/qemu/blob/master/linux-user/ptc.h) is part of our [qemu](https://github.com/revng/qemu) fork). We just published the instructions on how to [get started](https://rev.ng/getting-started.html).

If you any issue, please consider opening an issue on orchestra.
