### ISSUE TITLE
Build error using LLVM 10.0

### ISSUE THREAD

**Issue by mewmew** [revng/revng#13]
Hi @aleclearmind,

I tried to build rev.ng today. Very happy to see that the build times have been speed up by linking against the system-installed LLVM distribution!

When building the rev.ng project however, I ran into the following compile error:

```
$ make
Scanning dependencies of target revngSupport
[  4%] Building CXX object lib/Support/CMakeFiles/revngSupport.dir/DebugHelper.cpp.o
/tmp/revng/lib/Support/DebugHelper.cpp: In member function ‘void DebugHelper::generateDebugInfo()’:
/tmp/revng/lib/Support/DebugHelper.cpp:211:45: error: cannot convert ‘bool’ to ‘llvm::DINode::DIFlags’
  211 |                                             true, // isDefinition
      |                                             ^~~~
      |                                             |
      |                                             bool
In file included from /tmp/revng/lib/Support/DebugHelper.cpp:14:
/usr/include/llvm/IR/DIBuilder.h:666:56: note:   initializing argument 8 of ‘llvm::DISubprogram* llvm::DIBuilder::createFunction(llvm::DIScope*, llvm::StringRef, llvm::StringRef, llvm::DIFile*, unsigned int, llvm::DISubroutineType*, unsigned int, llvm::DINode::DIFlags, llvm::DISubprogram::DISPFlags, llvm::DITemplateParameterArray, llvm::DISubprogram*, llvm::DITypeArray)’
  666 |                    unsigned ScopeLine, DINode::DIFlags Flags = DINode::FlagZero,
      |                                        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [lib/Support/CMakeFiles/revngSupport.dir/build.make:122: lib/Support/CMakeFiles/revngSupport.dir/DebugHelper.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1585: lib/Support/CMakeFiles/revngSupport.dir/all] Error 2
make: *** [Makefile:161: all] Error 2
```

This was on rev 94a99fe57cf5ea7fbddbd0c260275799b08fd53b, with LLVM 10.0 installed on the system.

As indicated by the error, it seems like the API `Builder.createFunction` has been updated in LLVM 10.0.

Wish you all the best and happy reversing.

Cheers,
Robin

**Comment by mewmew** [comment]
A fix to the above build error could look as follows:

```diff
diff --git a/lib/Support/DebugHelper.cpp b/lib/Support/DebugHelper.cpp
index 7b2110d..4ab39a0 100644
--- a/lib/Support/DebugHelper.cpp
+++ b/lib/Support/DebugHelper.cpp
@@ -207,11 +207,12 @@ void DebugHelper::generateDebugInfo() {
                                             CompileUnit->getFile(),
                                             1, // Line
                                             EmptyType, // Subroutine type
-                                            false, // isLocalToUnit
-                                            true, // isDefinition
                                             1, // ScopeLine
                                             DINode::FlagPrototyped,
-                                            false /* isOptimized */);
+                                            DISubprogram::toSPFlags(
+                                              false, // isLocalToUnit
+                                              true,  // isDefinition
+                                              false) /* isOptimized */);
         F.setSubprogram(Subprogram);
       }
     }
```

**Comment by mewmew** [comment]
I also seem to get an error about `llvm::TerminatorInst` being undeclared, as this class has been deprecated in LLVM 10.0.

ref: https://reviews.llvm.org/rL340698

```
[  9%] Building CXX object lib/BasicAnalyses/CMakeFiles/revngBasicAnalyses.dir/GeneratedCodeBasicInfo.cpp.o
In file included from /tmp/revng/lib/BasicAnalyses/GeneratedCodeBasicInfo.cpp:18:
/tmp/revng/include/revng/BasicAnalyses/GeneratedCodeBasicInfo.h:70:27: error: ‘llvm::TerminatorInst’ has not been declared
   70 |   BlockType getType(llvm::TerminatorInst *T) const {
      |                           ^~~~~~~~~~~~~~
```

**Comment by aleclearmind** [comment]
Hi @mewmew.

1. Nope, we don't use system LLVM. Don't do that. Go through [orchestra](https://github.com/revng/orchestra). Build times should not be a big issues since, if you use orchestra, by default get prebuilt binary archives. If you have issues with orchestra or its binary archives, we're happy to work on them!
2. Internally, we use LLVM 9, most of the build issues you mentioned (and more) are already fixed.
3. Internally, we have support for LLVM 10 too. Waiting for the release of GCC 10 (which is late I think) to make big changes in orchestra only once.

We are quite busy, but soon we should get much better in pushing out things to the public.
In any case, just use orchestra. It is supposed to work here and now.

**Comment by mewmew** [comment]
Hi @aleclearmind,

Thanks for the quick response. I remember now that you were using orchestra to setup the build environment.

As I'll be doing a review and assessment of rev.ng (as part of reviewing the State of the Art in binary lifting for my Master's thesis), I'd love to work on the latest release.

Do you have any preliminary release schedule for the next release? Otherwise, would it be possible to get access to your internal version to use as bases for the evaluation?

Wish you all the best.

Kindly,
Robin

**Comment by aleclearmind** [comment]
I'll drop you an e-mail.
