### ISSUE TITLE
REGISTER_FS not in VariableManager::CPUStateGlobals

### ISSUE THREAD

**Issue by tvandera** [revng/revng#178]
Hi,

When _translating_ a static binary from x86_64 to x86_64, the [REGISTER_FS](https://github.com/revng/revng/blob/45ee99d5dec1696d811b1d632883e8de5eb2c911/runtime/support.h#L51) never ends up in the [VariableManager::CPUStateGlobals](https://github.com/revng/revng/blob/edaf468c7c12eb5bba104acffc35c05e6e64bbee/lib/Lift/VariableManager.h#L181), causing this code to fail.

https://github.com/revng/revng/blob/857f3afcf686271eaa79e5c9afdb3668db3e873c/runtime/support.c#L445-L450

Any idea is this is expected? How to fix it?

T.

**Comment by aleclearmind** [comment]
Mh, as a temporary solution you can invoke `Variables.getByEnvOffset($OFFSET, SPName)` in `CodeGenerator.cpp` after `GlobalVariable *SPReg = Variables.getByEnvOffset(ptc.sp, SPName).first`.
That should force the materialization.

However, if it's not materialized, the lifted code is probably not using it. Maybe also try:
```patch
diff --git a/lib/Lift/VariableManager.cpp b/lib/Lift/VariableManager.cpp
index a6d663ea..f1560097 100644
--- a/lib/Lift/VariableManager.cpp
+++ b/lib/Lift/VariableManager.cpp
@@ -468,8 +468,7 @@ void VariableManager::finalize() {
 
   // Populate the default case of the switch
   Builder.SetInsertPoint(DefaultBB);
-  Builder.CreateCall(TheModule.getFunction("abort"));
-  Builder.CreateUnreachable();
+  Builder.CreateRetVoid();
 
   // Create the switch statement
   Builder.SetInsertPoint(EntryBB);
```

**Comment by tvandera** [comment]
Thanks,

your suggested patch works fine.

T
