### ISSUE TITLE
revng translate fails to run if llvm is not installed

### ISSUE THREAD

**Issue by fuomag9** [revng/revng#18]
If llvm is not installed in the system (and the scripts do not install it as a dependency), revng will crash with this stacktrace

```
Traceback (most recent call last):
  File "revng/revng", line 495, in <module>
    sys.exit(main())
  File "revng/revng", line 479, in main
    return run_translate(command_args)
  File "revng/revng", line 271, in run_translate
    subprocess.check_call(log_command([get_command("llvm-link"),
  File "revng/revng", line 20, in get_command
    assert path
AssertionError
```

**Comment by aleclearmind** [comment]
Are you using `orchestra`?
Make sure you did the following in orchestra before running `revng`:

```
make revng
make environment
source environment
revng ...
```

**Comment by fuomag9** [comment]
> Are you using `orchestra`?
> Make sure you did the following in orchestra before running `revng`:
> 
> ```
> make revng
> make environment
> source environment
> revng ...
> ```

By doing this it worked
