### ISSUE TITLE
`make revng` will try to ssh to rev.ng

### ISSUE THREAD

**Issue by fuomag9** [revng/revng#19]
`make revng` will try to ssh to rev.ng, see log below.

```
[INFO] Fetching binary-archives/linux-x86-64/llvm-release/356e16fe702874e1c8679db9d08aaea00cb801ec_872a7e937993197e8fd622ffeeea82aa9dfc8d6b.tar.gz
The authenticity of host 'rev.ng (5.9.113.41)' can't be established.
ECDSA key fingerprint is SHA256:0Onr6gWpqUEfPoRZZVCPozbnYRz0d30odA3e+OuZpNA.
Are you sure you want to continue connecting (yes/no)? no [I manually had to deny/confirm]
Host key verification failed.
Downloading linux-x86-64/llvm-release/356e16fe702874e1c8679db9d08aaea00cb801ec_872a7e937993197e8fd622ffeeea82aa9dfc8d6b.tar.gz (876711074 bytes) from https://rev.ng/gitlab/revng/binary-archi...
[INFO] Extracting binary-archives/linux-x86-64/llvm-release/356e16fe702874e1c8679db9d08aaea00cb801ec_872a7e937993197e8fd622ffeeea82aa9dfc8d6b.tar.gz
```

**Comment by fuomag9** [comment]
It will try to continue to ssh for each download unless ssh fails to connect due to pubkey not being allowed

**Comment by aleclearmind** [comment]
Sadly the `binary-archives` (which provide rev.ng dependencies in binary form) are outdated.
We're going to publish the latest version of all our open source code soon.
In the meantime, you should still be able to build everything from source by completely disabling binary-archives:
```
export BINARY_COMPONENTS=""
make revng
```
This will take a while.

**Comment by aleclearmind** [comment]
This is outdated. Please check [the new orchestra repository](https://github.com/revng/orchestra) and report back.
