### ISSUE TITLE
Assertion failed at ... /StackAnalysis/Intraprocedural.h

### ISSUE THREAD

**Issue by chq-matteo** [revng/revng#22]
I am testing the decompiler over several binaries compiled from source code of programs the RosettaCode project https://github.com/acmeism/RosettaCodeData/tree/master/Lang/C 

I have found a few cases where the 'Abi Analysis Pass' does not terminate correctly.

I have collected the log, binaries and intermediate artifact in the attachments.

`report-2020-11-30.zip` contains the script used to decompile the binaries.

Each `a953a81dd22646f0883b3ff1ca6f52ed.lst.partXX.zip` contains a number of test cases.

Each testcase has:
- the command output in `stderr` and `stdout`
- files referenced in the dump under `./tmp` or `./home`
  - under `./tmp` you can find intermediate `ll` files
  - under `./home` you can find the binaries and the corresponding source code

[report-2020-11-30.zip](https://github.com/revng/revng/files/5617688/report-2020-11-30.zip)

[a953a81dd22646f0883b3ff1ca6f52ed.lst.part02.zip](https://github.com/revng/revng/files/5617855/a953a81dd22646f0883b3ff1ca6f52ed.lst.part02.zip)
[a953a81dd22646f0883b3ff1ca6f52ed.lst.part03.zip](https://github.com/revng/revng/files/5617856/a953a81dd22646f0883b3ff1ca6f52ed.lst.part03.zip)
[a953a81dd22646f0883b3ff1ca6f52ed.lst.part04.zip](https://github.com/revng/revng/files/5617861/a953a81dd22646f0883b3ff1ca6f52ed.lst.part04.zip)
[a953a81dd22646f0883b3ff1ca6f52ed.lst.part05.zip](https://github.com/revng/revng/files/5617865/a953a81dd22646f0883b3ff1ca6f52ed.lst.part05.zip)
[a953a81dd22646f0883b3ff1ca6f52ed.lst.part00.zip](https://github.com/revng/revng/files/5617866/a953a81dd22646f0883b3ff1ca6f52ed.lst.part00.zip)
[a953a81dd22646f0883b3ff1ca6f52ed.lst.part01.zip](https://github.com/revng/revng/files/5617869/a953a81dd22646f0883b3ff1ca6f52ed.lst.part01.zip)

**Comment by aleclearmind** [comment]
These tests no longer seem to fail. The following command exits successfully:

```
find -name "*.o" -print -exec revng artifact EnforceABI --analyze-all -o /dev/null {} \;
```
