### ISSUE TITLE
Build instructions in README should point to orchestra's

### ISSUE THREAD

**Issue by thebabush** [revng/revng#25]
The README in this repo is outdated.

**Comment by jeshan** [comment]
@aleclearmind @antoniofrighetto  Could you guide us?

The instructions on this page:
https://rev.ng/getting-started.html
looks outdated.

e.g the `support/install-dependencies.sh` is nowhere to be found.
`make test-revng install-revng` does not work neither.

All my other attempts have failed so far.

I have not got any nightly builds notifications as said on the website.

To attract users/contributors, there should be at least a way to get an executable / correct build instructions.

**Comment by antoniofrighetto** [comment]
Aye, thanks for reaching out. The instructions on the website are indeed outdated, we will update it soon, thanks! The website also links to how bootstrapping the new orchestra environment works ([here](https://github.com/revng/orchestra)). Also, consider joining [our discord](https://discord.com/invite/fJF2VrzdCJ), glad to help more there!

**Comment by jeshan** [comment]
Antonio,
Not sure what to do next. Should I follow the orchestra link or ask on discord?

**Comment by antoniofrighetto** [comment]
Both (: Try following the instructions at orchestra first, it should be easy to follow. If you find any issue with the configuration, feel free to ask us on discord - but join anyways.

**Comment by aleclearmind** [comment]
Fixed in 9cfc4e289d84718a446a1aeaca050075e3fda45d.
Thanks!
