### ISSUE TITLE
FromIRToExecutable.rst .li.csv file not created during lifting

### ISSUE THREAD

**Issue by mattr555-r** [revng/revng#271]
The instruction in FromIRToExecutable.rst mention that "revng lift" will create a .li.csv file with the same name as the output. This file is needed for linking the final program. This file is never create.

**Comment by aleclearmind** [comment]
That document is wildly outdated, we have a branch with new docs.

What's your goal?

If you want to perform full translation The Right Way™, use `revng translate`.

**Comment by mattr555-r** [comment]
My goal is to lift an executable to LLVM IR, make transformations, and then recompile back to executable. I know there are other possible tools with this capability, but those don't meet my needs. How can I recompile the IR produced by the "revng lift" command?

Also, where is the branch with new docs? I can't seem to find them.

**Comment by aleclearmind** [comment]
It's WIP unfortunately.

Run:
```
revng --verbose translate ...
```
It will print the commands that you should be able to replicate (and extend) with a script.

**Comment by mattr555-r** [comment]
Okay thanks

**Comment by aleclearmind** [comment]
You can use:

```
revng artifact --analyze recompile myprogram
```

Closing this, feel free to respond in case you still have problems.
