### ISSUE TITLE
Fuzzing with rev.ng and libfuzzer

### ISSUE THREAD

**Issue by aiglematth** [revng/revng#304]
Hello,

I am currently trying to reproduce the fuzzing post (https://rev.ng/blog/fuzzing/post.html) but as said in this issue (https://github.com/revng/revng/issues/57) we have netiher the LLVM passes nor the harness used. Is it possible to get the source code of these components ? I would be happy to try to interface them with the current release of revng.

Thanks by advance for your response :)
Matthieu

**Comment by aleclearmind** [comment]
I'm sorry but resuming that project is not an easy task and our focus has not been on fuzzing for a long time.

If you'd be interested in commercial support, drop me an e-mail `:)`
