### ISSUE TITLE
Documentation about commands equivalent to `revng translate` are not accurate

### ISSUE THREAD

**Issue by yomaytk** [revng/revng#308]
I tried to generate an executable binary from the LLVM IR generated by `revng lift`, using the following document as a reference.
https://github.com/revng/revng/blob/develop/docs/FromIRToExecutable.rst
However, when I get an error as shown below.

```
$ c++ -no-pie \
>     -Wl,-z,max-page-size=4096 \
>     -Wl,--section-start=.o_rx_0x400000=0x400000 \
>     -Wl,--section-start=.o_rw_0x416fb0=0x416fb0 \
>     -fuse-ld=bfd \
>     -Wl,--section-start=.elfheaderhelper=0x3fffff \
>     -Wl,-Ttext-segment=0x418000 \
>     translated.o \
>     -lz -lm -lrt -lpthread \
>     -o translated.elf.tmp

/home/user/workspace/compiler/orchestra/root/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/gcc-bin/11.2.0/../../../../lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld.bfd: translated.o: in function `main':
llvm-link:(.text+0x245d7): undefined reference to `phdr_address'
/home/user/workspace/compiler/orchestra/root/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/gcc-bin/11.2.0/../../../../lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld.bfd: llvm-link:(.text+0x245f4): undefined reference to `e_phentsize'
/home/user/workspace/compiler/orchestra/root/x86_64-pc-linux-gnu/x86_64-pc-linux-gnu/gcc-bin/11.2.0/../../../../lib/gcc/x86_64-pc-linux-gnu/11.2.0/../../../../x86_64-pc-linux-gnu/bin/ld.bfd: llvm-link:(.text+0x24611): undefined reference to `e_phnum'
collect2: error: ld returned 1 exit status
```

Now, I can exactly run the example of `hello.arm.translated` described in the README.md (https://github.com/revng/revng/blob/develop/README.md).

My environment is as follows.
```
OS: ubuntu20.04LTS
LLVM version: 16.0.1
```

Could anyone give me some advices?

**Comment by aleclearmind** [comment]
Unfortunately that documentation is not very up-to-date, we have a branch with improved documentation but it's not ready yet.

Why are you trying to run the commands by hand?
If you want to add extra linking flags, you can use `REVNG_TRANSLATE_LDFLAGS` or directly modify [`LinkForTranslation.cpp`](/https://github.com/revng/revng/blob/develop/lib/Recompile/LinkForTranslation.cpp#L148).

Does this help you?

**Comment by yomaytk** [comment]
Thank you for your advice.
I wanted to analyze the output LLVM IR and verify that the output LLVM IR is correctly executed by the LLVM backend. 
I hope the documentation will be updated.

Best Regards.

**Comment by aleclearmind** [comment]
OK, closing this. Feel free to open again in case.
