### ISSUE TITLE
`addressIsComparableWith(Other)` when lifting `/bin/bash`

### ISSUE THREAD

**Issue by JamesShaker** [revng/revng#311]
Hi there,

I attempted to use `revng` to lift `bash` inside a Ubuntu jammy based Docker image I created (
[`Dockerfile`](https://github.com/revng/revng/files/12141076/Dockerfile.txt) attached built with `docker build . -t revng`) with the following command sequence:
```
$ docker run --rm -it revng
root@XXXX:/work# cd /work/orchestra
root@XXXX:/work/orchestra# $HOME/.local/bin/orc shell
(orchestra) root@XXXX:/work/orchestra# revng lift /bin/bash /work/bash.bc
```

After about 5-10 seconds this fails with the following output (full stack dump output attached in 
[`stackdump.txt`](https://github.com/revng/revng/files/12141082/stackdump.txt)):
```
Check failed at /work/orchestra/sources/revng/include/revng/Support/MetaAddress.h:627

addressIsComparableWith(Other)
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
....
```

**Comment by aleclearmind** [comment]
Please attach the exact binary leading to a crash.

**Comment by aleclearmind** [comment]
Thanks! I've already seen this crash in our mass testing, will bump this in priority.

**Comment by aleclearmind** [comment]
I can no longer reproduce this on my branch. Once it's merged I'll close this.

**Comment by aleclearmind** [comment]
I can no longer reproduce this on `develop`. The binary you attached is lifted correctly.
Closing this, fell free to open a new issue if you encounter other problems.
