### ISSUE TITLE
Running `lli` on lifted code leads to "jit session error: symbols not found"

### ISSUE THREAD

**Issue by xwt1** [revng/revng#314]
the docs URL path is: https://github.com/revng/revng/blob/develop/docs/GeneratedIRReference.rst
I create a hello.c basicly like：
```
#include <stdio.h>

int main(){
    printf("hello");
    return 0;
}

```
And I use
``` 
x86_64-gentoo-linux-musl-gcc -static -O0 -fomit-frame-pointer hello.c -o hello
```
to compile ,and then I use revng to turn binary to ll
```
revng lift --debug-info ll hello hello.ll
```
but I find that hello.ll could not be opened by text editor , then i guess this should be bitcode(.bc) file?
what's wrong? All the tools and file path above is in my correct working directories path.

Except from it, Suppose the hello.ll actually is hello.bc , then I use llvm-dis in llvm version 16 to turn hello.bc into hello.ll and it seemed work, the hello.ll could be openned by text editor. But the content in it is too large and seems like it is not a "hello world" program. Then I use lli to run the hello.bc and also take a try in hello.ll, it failed with :
```
jit session error: symbols not found:,
```
I don't know what's wrong with my operation，Could someone please help me?

**Comment by aleclearmind** [comment]
> but I find that hello.ll could not be opened by text editor , then i guess this should be bitcode(.bc) file?

Yes, you can turn it into textual form using `revng opt -S`.
However that doc is kinda outdated, we have a branch with newer docs but it's not ready yet.

What are you trying to do? If you want to re-execute the program use `revng translate`, but that workflow is no longer primarily supported. We're focused on decompilation now.

**Comment by xwt1** [comment]
^_^Thanks for the response. I mainly want to  decompile the .ll(.bc) file which is produced by revng into executable file, which can be ran by the workflow below: 
Turn .ll file into .bc by using llvm-dis(llvm16) or revng opt -S like what you say . Then turn .bc file into .s file by using llc in llvm16. Finally, Turn .s file into executable file by using clang. But I find error when I obtained .s file . The .s file show something like :
![image](https://github.com/revng/revng/assets/61141245/1224fc0a-1d48-4245-8022-cb7ae17f11b7)
The normal (i use "clang -emit-llvm -c" to turn ".c" to ".bc" and then use "llc" to turn ".bc" to ".s") .s file is like:
![image](https://github.com/revng/revng/assets/61141245/9e404d0e-b802-4ef3-a330-e60f8182008e)
Then I use lli to verify the .bc file. The normal .bc file output is like:
![image](https://github.com/revng/revng/assets/61141245/30f4f0d0-d7e8-4fcf-8ebc-7284d6b20926)
The .bc file that revng output is like:
![image](https://github.com/revng/revng/assets/61141245/44e96fe6-ed2f-4ef1-ab1b-1ab104d049e3)
This is the problem that i state in the issue come from :"JIT session error: Symbols not found:" 
I think maybe the problem is that I use something outside the orchestra? Like llvm16 i use its lli and llc , which is not from the orchestra. I am glad to hear you soon~~

**Comment by aleclearmind** [comment]
1. Please do not paste screenshots of code
2. Use orchestra provided tools
3. As I said, try `revng --verbose translate`

**Comment by aleclearmind** [comment]
Yes, but there's no guarantee. As I mentioned, static binary translation is no longer our top priority.

**Comment by xwt1** [comment]
> Yes, but there's no guarantee. As I mentioned, static binary translation is no longer our top priority.
OK. Thanks for the response!

**Comment by aleclearmind** [comment]
Closing this. Feel free to reopen if you need more help.
