### ISSUE TITLE
Stack arguments not retrieved while enforcing ABI

### ISSUE THREAD

**Issue by aiglematth** [revng/revng#315]
Hello !

I am trying your enforce ABI option, and it seems not able to find the correct ABI for the following code : 

```c
extern "C" uint32_t Hard(uint8_t a, uint8_t b, uint8_t c, uint8_t d, uint8_t e, uint8_t f, uint8_t g, uint8_t h, uint8_t i, uint8_t j, uint8_t k, uint8_t l, uint8_t m) {
  return a + b + c + d + e + f + g + h + i + j + k + l + m;
}
```

After compile this code for the Aarch64 architecture and run the following commands to get the lifted binary with enforced ABI we obtain the following results :

```fish 
(orc) root[0]/t/test > ls
main.c
(orc) root[0]/t/test > aarch64-none-elf-c++ -static -nostdlib -O0 -fno-stack-protector  main.c -o main
/opt/arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf/bin/../lib/gcc/aarch64-none-elf/12.2.1/../../../../aarch64-none-elf/bin/ld: warning: cannot find entry symbol _start; defaulting to 0000000000400000
(orc) root[0]/t/test > ls
main  main.c
(orc) root[0]/t/test > file main
main: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), statically linked, not stripped
(orc) root[0]/t/test > revng analyze --resume debug ImportBinary main > /dev/null
(orc) root[0]/t/test > revng analyze --resume debug DetectABI main > /dev/null
(orc) root[0]/t/test > revng artifact --resume debug EnforceABI main > /dev/null
(orc) root[0]/t/test > ls debug/EnforceABI/
module.ll
(orc) root[0]/t/test > file debug/EnforceABI/module.ll
debug/EnforceABI/module.ll: ASCII text, with very long lines (37736)
```

```llvm-ir retrieved ABI
define i64 @local_Hard(i64 %x0_aarch64, i64 %x1_aarch64, i64 %x2_aarch64, i64 %x3_aarch64, i64 %x4_aarch64, i64 %x5_aarch64, i64 %x6_aarch64, i64 %x7_aarch64)
```

As you can see, stack arguments are not retrieved.
Am i missing something ?

Have a good day.

**Comment by aleclearmind** [comment]
Yes, stack arguments are detected using DLA, our unified analysis for data structures which also covers dissecting the stack frame and stack arguments.

DLA is not part of the open source revng project, but of our private set of analyses in revng-c. So that's normal.

If you'd like to get early access to revng-c (and the UI and everything), [register to our newsletter](https://rev.ng/register-for-nightly.html).

Feel free to reopen/comment if you still have doubts.
