### ISSUE TITLE
Remove `--disable-enforce-abi-safety-checks` option

### ISSUE THREAD

**Issue by andrealinux1** [revng/revng#36]
We should consider removing the `--disable-enforce-abi-safety-checks`.

This flag is used to decide if we want to emit a call to an opaque `function_dispatcher` (useful for decompilation) or a `switch` with inline calls (useful for translation).

We could instead emit both the structures, guarded by an `if` structure like this:
```
if (is_for_decompilation) {
  opaque_function_dispatcher();
} else {
  mega switch () {
  }
}
```
and rely on a later pass to substitute the `is_for_decompilation` condition with a constant, depending on what we want to have as output. Adequate standard optimizations should be used to purge away the useless alternative.

As an example, the pass `-prepare-for-decompilation` could do something like this:`replaceAllUseWith(is_for_decompilation, 1)`.

**Comment by aleclearmind** [comment]
I assume this issue is wildly outdated, closing it.
