### ISSUE TITLE
Crash when an instruction is partially out a segment

### ISSUE THREAD

**Issue by yangzao** [revng/revng#383]
Files: 
[1.zip](https://github.com/revng/revng/files/15151246/1.zip)
Source code, compiled program, and full error messages are included.

**Description**:

When decompiling the program, rev.ng gives error:
``
Assertion failed at /builds/gitlab/revng/orchestra/orchestra/sources/revng/lib/Support/IRHelpers.cpp:160
isPartOfRootDispatcher(Predecessor) == false
``

Compiler used: Clang (cross compile for Mach-O x86-64) with -O0
Version: 18.0.0

**Comment by aleclearmind** [comment]
I've a fix for this problem, will merge soon.

However, we do not currently support x86-64 macOS ABI, but #387 should fix that, should go in soon too.

Thanks for reporting this.

**Comment by aleclearmind** [comment]
This has been fixed and we now support the macOS ABI.
We still have a crash on DLA, but the following command works successfully:
```bash
revng artifact lift --analyses=import-binary,detect-abi,detect-stack-size,convert-functions-to-cabi -o /dev/null 1/a.out
```

Feel free to open a new issue if the problem persists.

Thanks for reporting this.
