### ISSUE TITLE
32-bit right shift operations using `i64` are not shrinked to `i32`

### ISSUE THREAD

**Issue by NaC-L** [revng/revng#392]
I decompiled this:
```cpp
int main(int argc, char* argv[]) {
	return (argc ^ 0x1337) >> 1;	
}
```

the result was kinda not very optimized
```cpp
_ABI(SystemV_x86_64)
generic64_t main(generic64_t _argument0, generic64_t _argument1) {
  typedef struct _PACKED _struct_1859 _struct_1859;
  struct _PACKED _struct_1859 {
    generic64_t _offset_0;
    generic32_t _offset_8;
    generic32_t _offset_12;
    uint8_t _padding_at_16[8];
  } _stack;
  _stack._offset_12 = 0;
  _stack._offset_8 = (number32_t) _argument0;
  _stack._offset_0 = _argument1;
  return (int64_t) ((number64_t) (_stack._offset_8 ^ 0x1336) << 32) >> 33 & 0xFFFFFFFF;
}
```

Now, you see the part `<< 32) >> 33 & 0xFFFFFFFF`, this doesnt make too much sense because we shift it by 32 bits to left and then 33 bits to right then and with 0xFFFF'FFFF (32 ones), I decided to dive into the lifting output. 

```llvm
%29619 = load i32, ptr %29618, align 1
%29620 = zext i32 %29619 to i64
store i64 %29620, ptr @rax, align 8
call void (ptr, i64, i32, i32, ptr, ptr, ...) @newpc(ptr nonnull @"revng.const.0x140001019:Code_x86_64", i64 5, i32 0, i32 0, ptr null, ptr null)
%29621 = load i64, ptr @rax, align 8
%29622 = xor i64 %29621, 4919
%29623 = and i64 %29622, 4294967295
store i64 %29623, ptr @rax, align 8
store i64 %29622, ptr @cc_dst, align 8
store i32 24, ptr @cc_op, align 4
call void (ptr, i64, i32, i32, ptr, ptr, ...) @newpc(ptr nonnull @"revng.const.0x14000101e:Code_x86_64", i64 2, i32 0, i32 0, ptr null, ptr null)
%29624 = load i64, ptr @rax, align 8
%sext33891 = shl i64 %29624, 32
%29625 = ashr exact i64 %sext33891, 32
%29626 = ashr i64 %sext33891, 33
%29627 = and i64 %29626, 4294967295
store i64 %29627, ptr @rax, align 8
```

as you can see, it is Sign Extending bits i32 to i64, then truncating the bits back to i32, the behavior is completely same with llvm's sext and truncate [as you can see here](https://alive2.llvm.org/ce/z/QnPgnG).

It would be more beneficial to both lifting and decompilation to not sign extend here to get a more readable output.
```llvm
(%29620 = zext i32 %29619 to i64)
%sext33891 = shl i64 %29624, 32
%29625 = ashr exact i64 %sext33891, 32
%29626 = ashr i64 %sext33891, 33
%29627 = and i64 %29626, 4294967295
```
=>
```llvm
%29626 = ashr i32 %29619, 1
``` 
(because its `sar eax, 1`)

https://alive2.llvm.org/ce/z/-swuox

Also, another issue with this is rax is not scaling down to eax and ax, it always lifts to i64 and i think that might be confusing for llvm because [if we scale our arguments to i64 we cant verify the same transform.](https://alive2.llvm.org/ce/z/y1xdAg) 

[Because when we have i64 values, we have to do the sext.](https://alive2.llvm.org/ce/z/i3Cwbm)

[example.zip](https://github.com/user-attachments/files/16014637/example.zip)

**Comment by aleclearmind** [comment]
OK, @andrealinux1 and I digged into the problem. The problem boils down to the fact that `type-shrinking` is not able to collapse `(x << 32) >> 33` on 64 bit integers to a `x >> 1`  on 32 bit integers.
It should be trivial to write a pass that does that running before `type-shrinking` which should then completely collapse the expression in what you're looking for.

I'll implement this and report back.

Thanks for reporting this! It was a quite interesting deep dive and I got to play around with Alive2 which is a pretty nice tool.

**Comment by NaC-L** [comment]
Thanks for looking into my issue!

> Also, another issue with this is rax is not scaling down to eax and ax, it always lifts to i64 and i think that might be confusing for llvm because [if we scale our arguments to i64 we cant verify the same transform.](https://alive2.llvm.org/ce/z/y1xdAg)

Its been a while so while I dont exactly remember what I was referring I think I was referring any operation with 32 bit registers are scaled to 64 bit, however not keeping track of the 32 higher part of bits.

`sar eax, 1; KnownBits: 00000000000000000000000000000000???????????????????????????????? `
`sar rax, 1; KnownBits: ????????????????????????????????????????????????????????????????`

`sar eax, 1` lifts to 
```
%29624 = load i64, ptr @rax, align 8
%sext33891 = shl i64 %29624, 32
%29625 = ashr exact i64 %sext33891, 32
%29626 = ashr i64 %sext33891, 33
%29627 = and i64 %29626, 4294967295
store i64 %29627, ptr @rax, align 8
```
but I think it should be possible to not sign extend eax to 64bits (or not sign extend anything at all?). I have created a fork to revng's qemu but I havent really tested it against other cases.

Or, dont sext/zext if we are going to truncate it anyways.

**Comment by aleclearmind** [comment]
> I have created a fork to revng's qemu

Touching the frontend (i.e., QEMU) won't be very effective. I think you're thinking that QEMU should be smart and stay in the 32 bits realm if the assembly uses `eax`, but I'd like to shrink things to 32-bits *even if* the input assembly was doing the `(x << 32) >> 33` thing by hand. This means that it's something that should be solved in the mid-end (i.e., on LLVM IR). This way, we will solve the problem for any other 64 bit architecture where you can do 32 bit arithmetic.

I created a [`feature/type-shrink-shr`](https://github.com/revng/revng/commits/feature/type-shrink-shr/) branch that fixes the problem. Basically there's [a new small pass](https://github.com/revng/revng/commit/64a1a16e6a5d948c300c6a649f66a949640d506f) that catches the `(x << 32) >> 33` pattern, which cannot be catched by the bitliveness-based TypeShrinking pass we have.

It should go in soon.

**Comment by aleclearmind** [comment]
It went in, can you try again and see if  it works?

By the way, I sent you an e-mail, did you get it?

**Comment by aleclearmind** [comment]
Closing this since we could verify this is fixed.
