### ISSUE TITLE
Build on windows

### ISSUE THREAD

**Issue by Nitr0-G** [revng/revng#395]
Hello everyone!) 
Is there a description somewhere of how to build revng on windows?

**Comment by Nitr0-G** [comment]
> Our roadmap is supporting Windows (we're at a good point there)
https://github.com/revng/revng/issues/89
https://github.com/revng/orchestra/pull/29
Is there any success?


P.S.
Found https://github.com/revng/orchestra/issues/152 - no support for windows

https://github.com/revng/orchestra

**Comment by aleclearmind** [comment]
We have a branch where things got to a good point on Windows, but as of now, it's not a top priority.

However, you can use WSL. Would that work for you?

**Comment by Nitr0-G** [comment]
> We have a branch where things got to a good point on Windows, but as of now, it's not a top priority.
> 
> However, you can use WSL. Would that work for you?

I want to integrate revng into some tools, so WSL is not really suitable, since the tools are large and rewriting them is not an option.

This branch https://github.com/revng/revng/tree/feature/windows ? 
If there is a revng build going on without problems during the build, then I could make a fork, update this branch as soon as possible to the state where the last stable branch is located and make a pull request

**Comment by aleclearmind** [comment]
> I want to integrate revng into some tools, so WSL is not really suitable, since the tools are large and rewriting them is not an option.

Consider that rev.ng has a client-server architecture, so you could spawn a revng-daemon somewhere (WSL, Docker, some remote machine) and then use the client from, e.g., Python, using your regular Windows environment.

> If there is a revng build going on without problems during the build, then I could make a fork, update this branch as soon as possible to the state where the last stable branch is located and make a pull request

On the revng side, you probably need very few changes, the big set of changes are on our build system, orchestra.
Here's the corresponding branch: https://github.com/revng/orchestra/compare/master...feature/windows.
We basically got all the dependencies to cross-compile but never did the last mile.
The branch is rather old but it should do 80% of the work.

Anyway, even with that branch, the goal is not to *develop* rev.ng under Windows, but just to produce a release build for Windows.

If you're into this effort, you should start from reviving orchestra's `feature/windows` branch.

**Comment by aleclearmind** [comment]
Developing `revng` on Windows is not currently supported.

We're going to offer builds for *running* rev.ng on Windows in the future. Closing this.
