### ISSUE TITLE
`revng lift` fails with `invalid choice: 'inject'`

### ISSUE THREAD

**Issue by 25pwn** [revng/revng#399]
I am trying to lift binaries to LLVM IR as part of a bigger project, and `rev.ng` looked like a good fit for the task. After looking through the docs and some code, I tried:
```
+ revng --verbose lift "$(command -v cat)" cat.ll
/home/user/state/orchestra/root/bin/revng \
  model \
  import \
  binary \
  /usr/bin/cat \
  -o \
  /tmp/revng-lift-xrpskmg2.yml

../root/libexec/revng/revng-model-import-binary \
  /usr/bin/cat \
  -o \
  /tmp/revng-lift-xrpskmg2.yml

/home/user/state/orchestra/root/bin/revng \
  model \
  inject \
  /tmp/revng-lift-xrpskmg2.yml \
  /dev/null \
  -o \
  /tmp/revng-lift-4dlgaiz2.ll

usage: revng model [-h] {import,compare,override-by-name,hard-purge,fetch-debuginfo,to-json,opt,apply,export-type-graph,dump,diff} ...
revng model: error: argument command_name1: invalid choice: 'inject' (choose from 'import', 'compare', 'override-by-name', 'hard-purge', 'fetch-debuginfo', 'to-json', 'opt', 'apply', 'export-type-graph', 'dump', 'diff')
```

It looks like `revng lift` is attempting to use removed code. Normally I'd try to debug this but I'm not familiar with `orc`. Is there a way to fix this? And is there a way to install a specified version of `revng` with `orc`?

**Comment by aleclearmind** [comment]
We really need to get rid of `revng lift`.
Use `revng artifact --analyze lift` and read the [docs](https://docs.rev.ng/).

**Comment by aleclearmind** [comment]
`revng lift` has been dropped in 99149c1b36950371d665e4eb4c32097f7b857c23.
