### ISSUE TITLE
`ptc.mmap`ing only `FileSize` bytes leads to translation failure in libtcg

### ISSUE THREAD

**Issue by 25pwn** [revng/revng#405]
I've tried rev.ng on quite a few vmprotect samples, and it crashes on some of them. Of a subset of 31 samples, 11 could not be lifted with `revng-artifact: /builds/gitlab/revng/orchestra/orchestra/sources/qemu/linux-user/ptc.c:388: TranslationBlock *tb_gen_code2(TCGContext *, CPUState *, target_ulong, target_ulong, int, int): Assertion `i != 256' failed.`.

This may be malware.
password: `infected`
[e02b4bb3e1739998dff2a165e2673ed4a580e4f7ba0d370c2b5424c2979478e9.zip](https://github.com/user-attachments/files/17009888/e02b4bb3e1739998dff2a165e2673ed4a580e4f7ba0d370c2b5424c2979478e9.zip)

**Comment by aleclearmind** [comment]
Fixed in 0126f0ce9b47919e093c0ce38599287fce204c65. Feel free to open more issues if you encounter additional problems.
