### ISSUE TITLE
Binaries with lots of invalid instructions take a long time to lift

### ISSUE THREAD

**Issue by Cvelth** [revng/revng#410]
An executable built from the attached sources with
```bash
orc shell aarch64-unknown-linux-musl-gcc -fno-pic -no-pie -static -std=c11 -O3 -Wall -DTARGET_aarch64 -Wl,--section-start=.text=0x2000000 -ggdb3 sample-type.c -ffreestanding -Wl,--entry=main -nostdlib -nodefaultlibs -o sample-type
```

Infinitely hangs (>4 minutes) on `Lifting: Peek new address` when doing
```bash
orc shell revng artifact decompile-to-single-file --analyze sample-type --progress 
```

[sample-type.zip](https://github.com/user-attachments/files/17255393/sample-type.zip)

It works just fine if `-Wl,--section-start=.text=0x2000000` option is not present.

**Comment by aleclearmind** [comment]
This should be fixed in ab0010b3f6b84e7750b9960aed1e728f3e2e7234. Please test and feel free to reopen if the problem persists.

Thanks for the report.
