### ISSUE TITLE
Function at entry point gets dropped during `isolate`

### ISSUE THREAD

**Issue by 25pwn** [revng/revng#415]
Similar issue to 09e483f.

The entry point in each binary is correctly lifted and dispatched to first in `@root` after `revng artifact lift`. However, it is dropped during `revng artifact isolate`.

reproducers:
> warning: these binaries are obfuscated LummaC2(malware) samples.
> password: `infected`

[samples.zip](https://github.com/user-attachments/files/17516593/samples.zip)

**Comment by aleclearmind** [comment]
Ah, this was a subtle bug. Should be fixed in efcea8ae481ed31b9069222f78d2be58d3132ba4.
Thanks for reporting, feel free to reopen if you can still reproduce the problem.
