### ISSUE TITLE
Files in `resume` have `.ll` extensions despite being `.bc.zst`

### ISSUE THREAD

**Issue by 25pwn** [revng/revng#419]
Presumably related to 8e65716

When using `--resume`, intermediate results(eg. `lift/module.ll`) have `.ll` extensions, but they are clearly not LLVM IR, nor bc. Piping `zstd -d` to `opt -S` reveals they are `.bc.zst`.

**Comment by aleclearmind** [comment]
Ah, we just noticed this today as well. Will fix soon.

`revng opt` was supposed to be able to handle those transparently, but we found out some limitations there.
Eventually, we'll change our fork of LLVM to handle `.zstd` transparently, I think.

**Comment by aleclearmind** [comment]
Fixed in ba186a130c5aa7475edf4bef13039e0ea83dfcdb (and in 30f4641 in revng-c).
Thanks for reporting this.

**Comment by aleclearmind** [comment]
Note: our version of `opt` now supports zstd compressed modules.
