### ISSUE TITLE
Packaging rev.ng for Arch Linux

### ISSUE THREAD

**Issue by D3vil0p3r** [revng/revng#422]
I would like to package this tool for Arch Linux. Can you please create a documentation that instructs how to build the tool from source?

Can you please also state a separated list for building dependencies and runtime dependencies needed by the tool?

**Comment by aleclearmind** [comment]
No, not at the this stage.

If you're not into using orchestra to build from source, use the binary distribution.

**Comment by D3vil0p3r** [comment]
Usually when we package tools, we should not use binaries. For this reason we need to build from source.

**Comment by aleclearmind** [comment]
Then use `orchestra`.
That's the only supported method. I can share with you a preliminary `flake.nix`, if you prefer.

But, again, currently, the only supported way to build from source is via orchestra. You can disable binary archives and *everything* will be built from source. It will take some time, but it will work.

**Comment by D3vil0p3r** [comment]
From docs I see that to build from source by `orchestra`, it is mandatory to use a config.yml file. Can you provide me a very simple `config.yml` contained in the "patch" example of https://docs.rev.ng/user-manual/working-environment/#building-from-source ?

**Comment by aleclearmind** [comment]
If you follow the instructions in that page, the `config.yml` will have been created for you and you just need to make the changes suggested by the patch.
Just follow the instructions. They work.

Do you want to build all the dependencies from source or just `revng` itself?

**Comment by D3vil0p3r** [comment]
I built `orchestra` by source and after the install I run `orc update` command I get:
```
[+] ERROR - Directory .orchestra not found!
```
I created manually `.orchestra`, rerun `orc update` and I get:
```
[+] INFO - This is the first time you run orchestra, welcome!
[+] INFO - Creating default user options in .orchestra/config/user_options.yml
[+] INFO - Populating default remotes for repositories and binary archives
[+] INFO - Remember to run `orc update` next
[+] ERROR - Could not get default remotes, manually configure .orchestra/config/user_options.yml
```

**Comment by aleclearmind** [comment]
You are most definitely not following the instructions in the guide.

Please report the exact commands to reproduce the problem.

**Comment by D3vil0p3r** [comment]
I needed to run `orc update` only under `orchestra` repository... but to do that `git lfs` is mandatory... Did you document it?
```
[+] INFO - This is the first time you run orchestra, welcome!
[+] INFO - Creating default user options in .orchestra/config/user_options.yml
[+] INFO - Populating default remotes for repositories and binary archives
[+] INFO - Remember to run `orc update` next
[+] INFO - Checking for redirects in https://github.com/revng/binary-archives
[+] INFO - Redirecting to https://rev.ng/gitlab/revng/binary-archives.git
[+] WARNING - The remote HEADs cache does not exist, you should run `orchestra update`
[+] ERROR - Could not invoke `git lfs`, is it installed?
```

**Comment by D3vil0p3r** [comment]
I have another doubt now... In order to build from source, once I patch the `config.yml` file, am I obligated to run `orc install --test revng revng-c` inside the `orchestra` repository? Or I can run everywhere?

**Comment by aleclearmind** [comment]
> git lfs is mandatory... Did you document it?

Nope. There's an `install-system-dependencies.sh` script that works for Ubuntu though.

> I obligated to run orc install --test revng revng-c inside the orchestra

`orc` is like git. You have to run it in a directory that contains (or whose parent contains) a `.orchestra` directory.

> when the process ends and I run revng stored in root/bin/ [...]

Please follow the docs:

```
orc shell
revng artifact
```

You're probably interested in `orc install revng-distributable` which creates in `root/revng` a self-contained installation of revng. It's what we use to build the release archive.

**Comment by D3vil0p3r** [comment]
Thank you @aleclearmind for all your information. I can close this ticket.
