### ISSUE TITLE
bug: test-translated-tests_runtime-translated_tests_runtime__global__arm-default is non deterministic

### ISSUE THREAD

**Issue by drblallo** [revng/revng#59]
Executing  test-translated-tests_runtime-translated_tests_runtime__global__arm-default on a release build can sometime crash.

```
120/128 Test #102: test-translated-tests_runtime-translated_tests_runtime__global__arm-default ........................................................***Failed    0.25 sec
Exception: A longjmp was taken ({ 0x29b84, 0x0, 0x0, 0x7 }
 -> { 0x29b84, 0x0, 0x0, 0x7 }
)
Exception: A longjmp was taken ({ 0x29b84, 0x0, 0x0, 0x7 }
 -> { 0x29b84, 0x0, 0x0, 0x7 }
)
Segmentation fault (core dumped)
```

The minimal setup on which we managed to reproduce the error is:
```
gdb --args orchestra/build/revng/optimized/share/revng/qa/tests/runtime/arm/translated/global nope
```
inside gdb:
```
set pagination off
set disable-randomization off

catch syscall 231
commands
run
end

run
```

The test should fail within a couple of hours. 
I have not been able to see the test fail when alsr was disabled.

We managed to get it to fail twice with randomization and in those two cases the stack pointer had different values.

The failing point was the same in both cases, it was the instruction at 0x00029bb0 in the original arm binary
```
00029b78 <__GI_brk>:
   29b78:	e92d4080 	push	{r7, lr}
   29b7c:	e1a03000 	mov	r3, r0
   29b80:	e3a0702d 	mov	r7, #45	; 0x2d
   29b84:	ef000000 	svc	0x00000000
   29b88:	e1530000 	cmp	r3, r0
   29b8c:	e59f2024 	ldr	r2, [pc, #36]	; 29bb8 <__GI_brk+0x40>
   29b90:	859f3024 	ldrhi	r3, [pc, #36]	; 29bbc <__GI_brk+0x44>
   29b94:	e08f2002 	add	r2, pc, r2
   29b98:	83a0100c 	movhi	r1, #12
   29b9c:	e5820000 	str	r0, [r2]
   29ba0:	8e1d2f70 	mrchi	15, 0, r2, cr13, cr0, {3}
   29ba4:	879f3003 	ldrhi	r3, [pc, r3]
   29ba8:	83e00000 	mvnhi	r0, #0
   29bac:	93a00000 	movls	r0, #0
>>>>   29bb0:	87821003 	strhi	r1, [r2, r3]
   29bb4:	e8bd8080 	pop	{r7, pc}
   29bb8:	00016d28 	andeq	r6, r1, r8, lsr #26
   29bbc:	000144c4 	andeq	r4, r1, r4, asr #9
```

The core dumps of the execution are attached [dumps.zip](https://github.com/revng/revng/files/6310796/dumps.zip) , they can be opened in gdb by
```
gdb orchestra/build/revng/optimized/share/revng/qa/tests/runtime/arm/translated/global dump.dump
```

llvm ir files are aviable but located in the wrong folder and gdb will fail to display them, it is enough to move them in the correct location.

**Comment by aleclearmind** [comment]
I assume this no longer happens. Feel free to reopen if it does
