### ISSUE TITLE
`install_pattern` usage causes confusion

### ISSUE THREAD

**Issue by Cvelth** [revng/revng#79]
[`install_pattern`](https://github.com/revng/revng/blob/45ee99d5dec1696d811b1d632883e8de5eb2c911/cmake/Common.cmake#L106) macro is a notorious for causing confusion because of being underexplained and not obvious for the users.

Most users don't expect build system to interact with the `git` repository, as a result, while moving headers around, faulty installations of unstaged changes cause unnecessary surprises (and related debugging).

Quoting @aleclearmind :
> I think we should just glob and stop using git for the time being

**Comment by aleclearmind** [comment]
You fixed this in 4c08f2153dfa5defdaf35ff5c52d74cbb517bdfd.
